volumes:
  pgadmin_data:
    driver: local

services:
  app:
    command: /bin/bash -c "bun install && bun run front:build && zig build run"
    environment:
      TZ: 'Asia/Tokyo'
      PORT: 5000
      DB_TYPE: 'postgresql'
      DB_USERNAME: 'postgres'
      DB_PASSWORD: 'postgres'
      DB_HOST: 'pg'
      DB_DATABASE: 'horizon_sample'
      CACHE_HOST: 'cache'
      CACHE_DB_NUMBER: 0
      CACHE_CONNECTION_TIMEOUT_MSECCONDS: 3000  # msec
      CACHE_TTL_SECONDS: 60  # sec
      SESSION_ENCRYPTION_KEY: 'session_encryption_key_session_encryption_key_session_encryption_key'
      SESSION_EXPIRE_SECONDS: 1296000  # 15 days
      MAIL_HOST: 'mailpit'
      MAIL_PORT: 1025
      MAIL_USERNAME: ''
      MAIL_PASSWORD: ''
      ADMIN_BASIC_AUTH_USERNAME: 'admin'
      ADMIN_BASIC_AUTH_PASSWORD: 'password123'
      API_CORS_ALLOW_ORIGIN: 'http://localhost:5000'
      API_CORS_ALLOW_METHODS: 'GET, POST, PUT, DELETE, OPTIONS'
      API_CORS_ALLOW_HEADERS: 'Content-Type, Authorization'
      API_CORS_ALLOW_CREDENTIALS: '1'
      API_CORS_MAX_AGE: '3600'
      VITE_API_KEY: 'apikey_apikey_apikey_apikey_apikey_apikey_apikey_apikey_apikey_apikey'
      VITE_URL_PREFIX: 'http://localhost:5000'
      VITE_ERROR_LOG: true
      VITE_PAYPAL_CLIENT_ID: 'test'

  pg:
    environment:
      DB_DATABASE: 'horizon_sample'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --locale=C.UTF-8'
      TZ: Asia/Tokyo
    ports:
      - "5432:5432"

  mysql:
    environment:
      MYSQL_DATABASE: 'horizon_sample'
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: 'password'
      TZ: 'Asia/Tokyo'
    ports:
      - "3306:3306"

  mailpit:
    environment:
      TZ: 'Asia/Tokyo'
    image: axllent/mailpit:latest
    ports:
      - "25016:8025"

  pgadmin:
    environment:
      PGADMIN_CONFIG_MAIL_SERVER: "'mailpit'"
      PGADMIN_CONFIG_MAIL_PORT: 1025
      PGADMIN_DEFAULT_EMAIL: 'yamamotok@harmonicom.jp'
      PGADMIN_DEFAULT_PASSWORD: 'pgadmin'
      TZ: 'Asia/Tokyo'
    image: dpage/pgadmin4:latest
    ports:
      - "54016:80"
    volumes:
      - type: volume
        source: pgadmin_data
        target: /var/lib/pgadmin

  phpmyadmin:
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: 'mysql'
      PMA_PORT: 3306
      PMA_USER: 'root'
      PMA_PASSWORD: 'password'
      TZ: 'Asia/Tokyo'
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "33016:80"

  autoheal: !reset
